name = "mayankrajoria"
compatibility_date = "2025-07-31"

[build]
command = "cd mayankrajoria && chmod a+x build.sh && ./build.sh"

[assets]
directory = "./mayankrajoria/public"
not_found_handling = "404-page"
